# Generated by Django 6.0.2 on 2026-02-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='color',
            field=models.CharField(choices=[('preto', 'Preto Brilho'), ('ptf', 'Preto Fosco'), ('branco', 'Branco Brilho'), ('bf', 'Branco Fosco'), ('vermelho', 'Vermelho'), ('azul', 'Azul'), ('dourado', 'Dourado Latão'), ('dourado ch', 'Dourado Champagne')], default='preto', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('pp', 'PP'), ('p', 'P'), ('m', 'M'), ('g', 'G'), ('gg', 'GG')], default='m', max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('shipped', 'Enviado'), ('delivered', 'Entregue')], default='pending', max_length=20),
        ),
    ]
