# Generated by Django 6.0.2 on 2026-02-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_color_order_size_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='color',
            field=models.CharField(choices=[('preto', 'Preto Brilho'), ('preto fosco', 'Preto Fosco'), ('branco brilho', 'Branco Brilho'), ('branco fosco', 'Branco Fosco'), ('vermelho', 'Vermelho'), ('azul', 'Azul'), ('dourado latão', 'Dourado Latão'), ('dourado champagne', 'Dourado Champagne')], default='preto', max_length=20),
        ),
    ]
