# Generated by Django 6.0.2 on 2026-02-19 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=120)),
                ('customer', models.CharField(max_length=120)),
                ('quantity', models.PositiveIntegerField()),
                ('color', models.CharField(choices=[('black', 'Preto'), ('white', 'Branco'), ('red', 'Vermelho'), ('blue', 'Azul'), ('green', 'Verde')], default='black', max_length=20)),
                ('size', models.CharField(choices=[('pp', 'PP'), ('p', 'P'), ('m', 'M'), ('g', 'G'), ('gg', 'GG')], default='m', max_length=5)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
